version: '3.8'

services:
  crypto-monitor:
    image: crypto-monitor:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-monitor
    restart: always
    env_file:
      - .env
    environment:
      # Configuraciones generales
      PORT: ${PORT:-3000}
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Configuraciones específicas por red
      TRON_MAX_CONFIRMATIONS: ${TRON_MAX_CONFIRMATIONS:-41}
      ETHERSCAN_API_KEYS: ${ETHERSCAN_API_KEYS}
      USDT_CONTRACT_ADDRESS: ${USDT_CONTRACT_ADDRESS}
      ERC20_MAX_CONFIRMATIONS: ${ERC20_MAX_CONFIRMATIONS:-12}
      POLYGONSCAN_API_KEYS: ${POLYGONSCAN_API_KEYS}
      POLYGON_MAX_CONFIRMATIONS: ${POLYGON_MAX_CONFIRMATIONS:-12}
      TRX_MAX_CONFIRMATIONS: ${TRX_MAX_CONFIRMATIONS:-41}
      XRP_MAX_CONFIRMATIONS: ${XRP_MAX_CONFIRMATIONS:-6}

    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

