version: '3.8'

services:
  crypto-monitor:
    image: crypto-monitor:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-monitor
    restart: always
    env_file:
      - .env
    environment:
      # Configuraciones generales
      PORT: ${PORT:-3000}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}

      # Configuraciones específicas
      TRON_MAX_CONFIRMATIONS: ${TRON_MAX_CONFIRMATIONS:-41}
      ERC20_MAX_CONFIRMATIONS: ${ERC20_MAX_CONFIRMATIONS:-12}
      POLYGON_MAX_CONFIRMATIONS: ${POLYGON_MAX_CONFIRMATIONS:-12}
      XRP_MAX_CONFIRMATIONS: ${XRP_MAX_CONFIRMATIONS:-6}
      BEP20_MAX_CONFIRMATIONS: ${BEP20_MAX_CONFIRMATIONS:-12}
      ARBITRUM_MAX_CONFIRMATIONS: ${ARBITRUM_MAX_CONFIRMATIONS:-12}
      BTC_MAX_CONFIRMATIONS: ${BTC_MAX_CONFIRMATIONS:-6}
      MULTICHAIN_API_KEYS: ${MULTICHAIN_API_KEYS}
      USDT_CONTRACT_ADDRESS: ${USDT_CONTRACT_ADDRESS}

      # Intervalos de sondeo
      POLLING_INTERVAL_ACTIVE: ${POLLING_INTERVAL_ACTIVE:-30000}
      POLLING_INTERVAL_IDLE: ${POLLING_INTERVAL_IDLE:-3600000}

    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"